version: '3.7'

services: 
  # api
  url-shortener-backend: 
    container_name: url-shortener-python
    build: ./
    # command: flask run
    working_dir: /usr/src/url-shortener-python
    environment: 
      FLASK_APP: server.py
      FLASK_DEBUG: 'true'
      FLASK_ENV: development
    links: 
      - redis
    ports: 
      - "5000:5000"
    volumes: 
      - .:/usr/src/url-shortener-python

  # redis db
  redis: 
    image: redis
    ports: 
      - "6379:6379"
      