version: '3.7'

services: 
  # api
  url-shortener-api: 
    container_name: url-shortener
    build: ./
    # command: flask run
    working_dir: /usr/src/url-shortener
    environment: 
      FLASK_APP: server.py
      FLASK_DEBUG: 'true'
      FLASK_ENV: development
      REDIS_URI: redis://redis:6379
    links: 
      - redis
    ports: 
      - "5000:5000"
    volumes: 
      - .:/usr/src/url-shortener

  # redis db
  redis: 
    image: redis
    ports: 
      - "6379:6379"